
import request from '@/utils/request'

export function qaFinishFabricInspectionTaskInfo(data = {}) {
  return request({
    url: '/qa/qaFinishFabricInspectionTask/info',
    method: 'post',
    data: data
  })
}

// 渲染列表
export function qaFinishFabricInspectionTaskList(data = {}) {
  return new Promise(function(resolve, reject) {
    const result = {
      code: 200,
      data: [
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 1,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '疵点\\扣分',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 2,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '飞花/尼龙草',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 2,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '烂边',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 2,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '烂针',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 2,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '漏针',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 2,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '断纱',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 2,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '剪洞',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 4,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '染花',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 5,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '起横',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 6,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '实封/边封',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 7,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '重量/码长',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 82,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '含潮测试',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 8,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '总分',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        },
        { createdBy: '苑玉林',
          createdTime: 1620812715000,
          gradeRule: 'nt',
          id: 9,
          isEnabled: true,
          isRelationYarnGrade: false,
          name: '验布结果(匹)',
          nameEn: null,
          orders: 0,
          remarks: null,
          revision: 5,
          status: 'Y',
          updatedBy: '（๑ `▽´๑)',
          updatedTime: 1622113881000,
          uuid: '7f2d1c943bf4439e8bf5ffa7bf92dff1'
        }
      ]
    }
    resolve(result)
  })
  // return request({
  //   url: '/baseData/qa/finishedFabricOtherProjects/list',
  //   // url: 'https://yapi.szhibu.com/mock/221/qa/qaFinishFabricInspectionTask/info',
  //   method: 'post',
  //   data: { ...data }
  // })
}

// 成品验布-编辑
export function qaFinishFabricInspectionTaskModify(data = {}) {
  return request({
    url: '/qa/qaFinishFabricInspectionTask/modify',
    method: 'post',
    data: data
  })
}

// 成品验布-审核
export function qaFinishFabricInspectionTaskAudit(data = {}) {
  return request({
    url: '/qa/qaFinishFabricInspectionTask/audit',
    method: 'post',
    data: data
  })
}

