const staticFile = {
  // tabProp: [
  //   { name: '订单号' },
  //   { name: '交期' },
  //   { name: '产品编码' },
  //   { name: '数量kg' },
  //   { name: '布类' },
  //   { name: '纱名' },
  //   { name: '纱属性' },
  //   { name: '成份比例' },
  //   { name: '成衣部位' },
  //   { name: '款号' },
  //   { name: '幅宽' },
  //   { name: '克重' },
  //   { name: '客户颜色' },
  //   { name: '颜色分类' },
  //   { name: '生产流程' },
  //   { name: '工艺要求' },
  //   { name: '理论纱期' },
  //   { name: '目标纱期' },
  //   { name: '采购复期' },
  //   { name: '纱期送审' },
  //   { name: '理论色纱期_S' },
  //   { name: '理论色纱期_E' },
  //   { name: '理论坯期_S' },
  //   { name: '理论坯期_E' },
  //   { name: '理论色布期_S' },
  //   { name: '理论色布期_E' },
  //   { name: '计划开始色纱期' },
  //   { name: '计划结束色纱期' },
  //   { name: '计划开始坯期' },
  //   { name: '计划结束坯期' },
  //   { name: '计划开始色布期' },
  //   { name: '计划结束色布期' },
  //   { name: '计划开始印花布期' },
  //   { name: '计划结束印花布期' },
  //   { name: '计划复期' },
  //   { name: '交期确认' },
  //   // { name: '急单' },
  //   { name: '理论花布期_S' },
  //   { name: '理论花布期_E' },

  //   { name: '区域' },
  //   { name: '销售员' },
  //   { name: '计划备注' }
  // ],
  tabPropTop: [
    { name: '订单号' },
    { name: '交期' },
    { name: '成衣ID' },
    { name: '成衣部位' },
    { name: '数量kg' },
    { name: '生产流程' },
    { name: '目标纱期' },
    { name: '采购复期' },
    { name: '计划结束色纱期' },
    { name: '计划结束坯期' },
    { name: '计划结束色布期' },
    { name: '计划结束印花布期' },
    { name: '计划复期' },

    { name: '客户' },
    { name: '客服' },

    { name: '客户颜色' },

    { name: '色级' },
    { name: '布类' },
    { name: '纱名' },
    { name: '纱属性' },
    { name: '成份比例' },
    // { name: '产品编码' },
    { name: '工艺要求' },
    { name: '交期确认' }

  ],
  tabPropBottom: [
    { name: '幅宽' },
    { name: '克重' },
    { name: '款号' },
    { name: '区域' },
    { name: '销售员' },
    { name: '急单' },
    { name: '计划备注' },
    { name: '纱期送审' },

    { name: '针数' },
    { name: '寸数' },
    { name: '总针数' },
    { name: '智布色号' },

    { name: '理论纱期' },
    { name: '理论色纱期_S' },
    { name: '理论色纱期_E' },
    { name: '理论坯期_S' },
    { name: '理论坯期_E' },
    { name: '理论色布期_S' },
    { name: '理论色布期_E' },
    { name: '理论印花布期_S' },
    { name: '理论印花布期_E' },
    { name: '计划开始色纱期' },
    { name: '计划开始坯期' },
    { name: '计划开始色布期' },
    { name: '计划开始印花布期' }
    // { name: '计划复期' },
  ],
  btnList: [
    { text: '目标纱期', prop: 'targetYarnDate', type: '_date', permission: 'aps-center:planSchedule:modifyTargetYarnDate' },
    { text: '计划色纱期', prop: 'planCloseColorYarnDate', type: '_date', permission: 'aps-center:planSchedule:modifyPlanCloseColorYarnDate' },
    { text: '计划坯期', prop: 'planCloseGreyDate', type: '_date', permission: 'aps-center:planSchedule:modifyPlanCloseGreyDate' },
    { text: '计划色布期', prop: 'planCloseColorClothDate', type: '_date', permission: 'aps-center:planSchedule:modifyPlanCloseColorClothDate' },
    { text: '计划印花期', prop: 'planClosePrintClothDate', type: '_date', permission: 'aps-center:planSchedule:modifyPlanClosePrintClothDate' },
    { text: '计划复期', prop: 'planDelivery', type: '_date', permission: 'aps-center:planSchedule:modifyPlanDelivery' },
    { text: '交期确认', prop: 'deliveryConfirm', type: '_date', permission: 'aps-center:planSchedule:deliveryConfirm' }

  ]
}

export default staticFile
